name: "Multilevel F1 with No Thinking"
description: "Don't use thinking"

reward:
  - fn: multilevel_localization_f1_reward
    weight: 1.0
    args:
      beta: 0.5
  - fn: format_reward
    weight: 1.0
    args:
      penalize: false

tools:
  - glob
  - grep
  - terminal

prompts:
  system_prompt: "templates/system_prompt.j2"
  user_prompt: "templates/file_module.j2"