name: "Multilevel F1 with No Thinking"
description: "Don't use thinking"

reward:
  - fn: multilevel_localization_f1_reward

tools:
  - glob
  - grep
  - terminal

prompts:
  system_prompt: "templates/system_prompt_short.j2"
  user_prompt: "templates/file_module_no_think.j2"